services:
  muf-up:
    build: .
    container_name: muf-up
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.muf-up.rule=Host(`muf-up.masmuf.cloud`)"
      - "traefik.http.routers.muf-up.entrypoints=websecure"
      - "traefik.http.routers.muf-up.tls.certresolver=myresolver"
      - "traefik.http.services.muf-up.loadbalancer.server.port=80"

networks:
  web:
    external: true
